"""Add description field to Book model

Revision ID: 3a60b9e00e52
Revises: b2d1c8f4d1a9
Create Date: 2025-06-14 17:46:03.102242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a60b9e00e52'
down_revision: Union[str, None] = 'b2d1c8f4d1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_user_books_id'), 'user_books', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_books_id'), table_name='user_books')
    op.drop_column('books', 'description')
    # ### end Alembic commands ###
